# Generated by Django 4.2.15 on 2024-08-11 10:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('postcode', models.CharField(default='', max_length=255)),
                ('napa_id', models.CharField(default='', max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'DISTRICTS',
                'db_table': 'districts',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('postcode', models.CharField(default='', max_length=255)),
                ('napa_id', models.CharField(default='', max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'REGIONS',
                'db_table': 'regions',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('postcode', models.CharField(default='', max_length=255)),
                ('napa_id', models.CharField(default='', max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_district', to='workshop.district')),
            ],
            options={
                'verbose_name_plural': 'WARDS',
                'db_table': 'wards',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('postcode', models.CharField(default='', max_length=255)),
                ('napa_id', models.CharField(default='', max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='street_ward', to='workshop.ward')),
            ],
            options={
                'verbose_name_plural': 'STREETS',
                'db_table': 'streets',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_region', to='workshop.region'),
        ),
    ]
